[project]
name = "gb-t-35000-2014-implementation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coolprop>=7.2.0",
    "numpy>=2.3.5",
    "pyaga8>=0.1.15",
]
